version: 2

models:
  - name: sample_snowflake_table__sample
    database: DEMODB_1  
    schema: PUBLIC
    description: "sample data" 
    tables:
      - name: new
        description: "about table"

